# Generated by Django 3.2 on 2022-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0),
        ),
    ]
