# Generated by Django 3.2 on 2022-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220506_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
