# Generated by Django 3.2 on 2022-05-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todolist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='slug',
        ),
    ]
