# Generated by Django 3.2 on 2022-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todolist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
