# Generated by Django 3.2 on 2022-05-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uservotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
